developer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('foody.urls'), name='foody-urls'),
    path('about/', include('about.urls'), name='about-urls'),
    path('accounts/', include('allauth.urls')),
    path('menu/', include('menu.urls'), name='menu-urls'),
    path('order_cart_add/', include('ordercart.urls')),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.MenuList.as_view(), name='menu'),
    path('<slug:slug>/', views.menu_detail, name='menu_detail'),
    path('<slug:slug>/edit_comment/<int:comment_id>', views.customer_comment_edit, name='customer_comment_edit'),
    path('<slug:slug>/delete_comment/<int:comment_id>', views.customer_comment_delete, name='customer_comment_delete'),
]

menu/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Menu(models.Model):
    menu_title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    customer = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='restaurant_menus'
    )
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name='category'
    )
    featured_image = CloudinaryField('image', default='placeholder')
    description = models.TextField(blank=True, null=True)
    price = models.PositiveIntegerField()

    def __str__(self):
        return self.menu_title


class CustomerComment(models.Model):
    meal = models.ForeignKey(
        Menu, on_delete=models.CASCADE, related_name='comments'
    )
    customer = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='commenter'
    )
    text = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    rating = models.PositiveIntegerField(default=False)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return f"Comment {self.text} by {self.customer}"

menu/forms.py
from .models import CustomerComment
from django import forms


class CustomerCommentForm(forms.ModelForm):
    class Meta:
        model = CustomerComment
        fields = ('text',)

menu/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic
from django.contrib import messages
from django.http import HttpResponseRedirect
from .models import Menu, CustomerComment
from .forms import CustomerCommentForm


# Create your views here.
class MenuList(generic.ListView):
    queryset = Menu.objects.all()
    template_name = "menu/menu.html"


def menu_detail(request, slug):
    """
    Display an individual :model:`menu.Menu`.

    **Context**

    ``post``
        An instance of :model:`menu.Menu`.

    **Template:**

    :template:`menu/menu_detail.html`
    """
    queryset = Menu.objects.all()
    meal = get_object_or_404(queryset, slug=slug)
    customer_comments = meal.comments.all().order_by("-created_on")

    if request.method == "POST":
        customer_form = CustomerCommentForm(data=request.POST)
        if customer_form.is_valid():
            comment = customer_form.save(commit=False)
            comment.customer = request.user
            comment.meal = meal
            comment.save()
        messages.add_message(
            request, messages.SUCCESS,
            'Comment submitted!'
        )

    customer_form = CustomerCommentForm()

    return render(
        request,
        "menu/menu_detail.html",
        {
            "meal": meal,
            "customer_comments": customer_comments,
            "customer_form": customer_form,
        },
    )


def customer_comment_edit(request, slug, comment_id):
    """
    view to edit comments
    """
    if request.method == "POST":
        queryset = Menu.objects.all()
        meal = get_object_or_404(queryset, slug=slug)
        customer_comments = get_object_or_404(CustomerComment, pk=comment_id)
        customer_form = CustomerCommentForm(
            data=request.POST, instance=customer_comments)

        if customer_form.is_valid() and customer_comments.customer == request.user:
            comment = customer_form.save(commit=False)
            comment.meal = meal
            comment.save()
            messages.add_message(request, messages.SUCCESS, 'Comment Updated!')
        else:
            messages.add_message(
                request, messages.ERROR, 'Error updating comment!')

    return HttpResponseRedirect(reverse('menu_detail', args=[slug]))


def customer_comment_delete(request, slug, comment_id):
    """
    view to delete comments
    """
    queryset = Menu.objects.all()
    meal = get_object_or_404(queryset, slug=slug)
    customer_comments = get_object_or_404(CustomerComment, pk=comment_id)

    if customer_comments.customer == request.user:
        customer_comments.delete()
        messages.add_message(request, messages.SUCCESS, 'Comment deleted!')
    else:
        messages.add_message(
            request, messages.ERROR, 'You can only delete your own comments!')

    return HttpResponseRedirect(reverse('menu_detail', args=[slug]))


def order_details(request, slug, ):
    """
    view customer order
    """
    queryset = Menu.objects.all()
    

menu/templates/menu/menu.html
{% extends "base.html" %}
{% load static %}
{% block content %}

 
{% comment %} <div class="container">
    <div class="row">
        <div class="col">
            
            {% for menu in menu_list %}
                <div class="col-md-4">
                    <img src="{% static 'images/logo.jpg' %}" class="img-fluid rounded-start" alt="placeholders">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in menu.featured_image.url %}
                                <img class="card-img-top" src="{% static 'images/logo.jpg' %}" alt="placeholder image">
                                {% else %}
                                <img class="card-img-top" src="{{ menu.featured_image.url }}" alt="{{ menu.menu_title }}">
                                <div class="image-flash">
                                    <h2 class="card-title">{{ menu.menu_title }}</h2> 
                                </div>
                            </div>
                            <p class="card-text">€{{ menu.price }}</p>
                            <a href="{% url 'menu_detail' menu.slug %}" class="post-link"> 
                            </a>
                            <hr /> 
                        </div>
                    </div>
                </div>
                 {% if menu.category == |divisibleby:2 %} 
            </div>
            <div class="row"> 
                 {% endif %} 
                {% endfor %}
            </div>
            
        </div>
    </div>
</div> {% endcomment %}
<div class="container-fluid">
    <div class="row">
        <!-- Blog Entries Column -->         
        <div class="col-12 mt-3 left">
            <div class="row">            
                {% for menu in menu_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                <img class="card-img-top" src="{{ menu.featured_image }}" alt="{{ menu.menu_title }}">
                                <div class="image-flash">
                                    <h2 class="card-title">{{ menu.menu_title }}</h2>                                    
                                </div>
                            </div>
                            <p class="card-text">€{{ menu.price }}</p>
                            <a href="{% url 'menu_detail' menu.slug %}" class="post-link">View meal details 
                            </a>
                            <hr />                            
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %} 
            </div>
            <div class="row"> 
                {% endif %} 
                {% endfor %}
            </div>           
        </div>
    </div>
</div>


{% comment %} <div class="container text-center">
    <div class="row"> 
        {% for menu in menu_list %}
        <div class="card mb-3" style="max-width: 540px;">
            <div class="row g-0">
        
                <div class="col-md-4">
                    <img src="{% static 'images/logo.jpg' %}" class="img-fluid rounded-start" alt="placeholders">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">{{ menu.menu_title }}</h5>
                        <p class="card-text"><small class="text-muted">€ {{ menu.price }}</small></p>
                        <a href="{% url 'menu_detail' menu.slug %}" class="menu-details">View meal detail.</a>
                    </div>
                </div>
                    {% if forloop.counter|divisibleby:2 %}
                    <div class="row">
                    {% endif %} 
                    </div>
                    
            </div>
        </div>
        {% endfor %} 
     </div>
</div>  {% endcomment %}
        
{% comment %} <div class="container-fluid">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for post in post_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                <div class="image-flash">
                                    <p class="author">Author: {{ post.author }}</p>
                                </div>
                            </div>
                            <a href="#" class="post-link">
                                <h2 class="card-title">{{ post.title }}</h2>
                            </a>

                            <hr />
                            <p class="card-text text-muted h6">{{ post.created_on}}
                            </p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}

            </div>
        </div>
    </div> {% endcomment %}
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

<!-- index.html content ends here -->
{% endblock %}

menu/templates/menu/menu_detail.html
{% extends 'base.html' %} 
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<div class="card m-auto" style="width: 30%">
    <div class="card-body">
        <h5 class="card-title">{{ meal.menu_title }}</h5>
        <p class="card-text">{{ meal.description | safe }}</p>
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
          <button id="submitButton" type="submit" class="btn btn-submit">Submit</button>
          <button class="btn btn-delete" comment_id="{{ comment.id }}">Delete</button>
        </div>
    </div>
    <img src="{{ menu.featured_image.url }}" class="card-img-bottom" alt="placeholders">
</div>

<div class="container">
  <!-- Displaying Comments -->
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 ">
      <h3>Customer comments:</h3>
      <div class="card-body">
        <!-- We want a for loop inside the empty control tags
          to iterate through each comment in comments -->
        {% for comment in customer_comments %}
        <div class="p-2 comments
          {% if not comment.customer == user %}
          faded{% elif not comment.customer %} d-none{% endif %}">
          <p class="font-weight-bold">
            {{ comment.customer }}
            <span class="font-weight-normal">
              {{ comment.created_on }}
            </span> wrote:
          </p>
          <div id="comment{{ comment.id }}">
            {{ comment.text | linebreaks }}
          </div>
          {% comment %} {% if not comment.customer == user %}
          <p class="approval">
            This comment is awaiting approval
          </p>
          {% endif %} {% endcomment %}
          {% if user.is_authenticated and comment.customer == user %}
          <button class="btn btn-delete" comment_id="{{ comment.id }}">Delete</button>
          <button class="btn btn-edit" comment_id="{{ comment.id }}">Edit</button>
          {% endif %}
        </div>
        <!-- Our for loop ends here -->
        {% endfor %}
      </div>
    </div>
  </div>
    <!-- Displaying reviews -->
  {% comment %} <div class="row">
    <div class="col-12">
        {% for review in ratings %}
      <strong class="text-secondary"><i class="far fa-comments"></i>{{ review.customer }} | {{ review.rating }}</strong>
      {% if review.rating == 5 %}⭐⭐⭐⭐⭐
      {% elif review.rating == 4 %}⭐⭐⭐⭐
      {% elif review.rating == 3 %}⭐⭐⭐
      {% elif review.rating == 2 %}⭐⭐
      {% else %}⭐
      {% endif %}
      {% endfor %}
    </div>
    <div class="col-12">
      <hr>
    </div>
  </div> {% endcomment %}
  
      </div>
    </div>
    <!-- Creating New Comments -->
    <div class="col-md-4 card mb-4 mt-3">
      <div class="card-body">
        {% if user.is_authenticated %}
        <h3>Leave a comment:</h3>
        <p>Commenting as: {{ user.customer }}</p>
        <form id="customerForm" method="post" style="margin-top: 1.3em;">
          {{ customer_form | crispy }}
          {% csrf_token %}
          <button id="submitButton" type="submit" class="btn btn-signup btn-lg">Submit</button>
        </form>
        {% else %}
          <p>Log in to leave a comment</p>
        {% endif %}
        </div>
    </div> 
  </div>
</div> 

<!-- Delete confirmation modal -->
<div class="modal fade" id="deleteModal" tabindex="-1"
  aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"
          id="deleteModalLabel">Delete comment?</h5>
        <button type="button" class="btn-close"
          data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete your comment?
        This action cannot be undone.
      </div> 
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary"
          data-bs-dismiss="modal">Close</button>
        <a id="deleteConfirm" href="#" class="btn
          btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>

{% endblock content %}
{% block extras %}
<script src="{% static 'js/comments.js' %}"></script>
{% endblock %}  